# Generated by Django 4.0.2 on 2023-02-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jannah_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'feedback', 'verbose_name_plural': '7. Feedbackss'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': 'workflow', 'verbose_name_plural': '8. Workflows'},
        ),
    ]
