# Generated by Django 4.0.2 on 2023-12-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jannah_site', '0002_alter_feedback_options_alter_workflow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'feedback', 'verbose_name_plural': '8. Feedbackss'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'site', 'verbose_name_plural': '1. Sites'},
        ),
        migrations.AlterModelOptions(
            name='ux',
            options={'verbose_name': 'ux', 'verbose_name_plural': '7. UXs'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': 'workflow', 'verbose_name_plural': '9. Workflows'},
        ),
        migrations.AddField(
            model_name='workflow',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
